# Generated by Django 5.1.6 on 2025-02-22 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('_yield', models.DecimalField(decimal_places=2, max_digits=100)),
                ('indoor', models.BooleanField(null=True)),
                ('cycle', models.CharField(max_length=200)),
                ('watering', models.CharField(max_length=200)),
                ('watering_avg_volume_requirement', models.IntegerField(null=True)),
                ('pruning_month', models.CharField(max_length=200, null=True)),
                ('growth_rate', models.CharField(max_length=200, null=True)),
                ('min_hardiness', models.IntegerField(null=True)),
                ('max_hardiness', models.IntegerField(null=True)),
                ('image_url', models.URLField(null=True)),
                ('sunlight', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_planted', models.DateTimeField(auto_now_add=True)),
                ('last_watered', models.DateTimeField(auto_now=True)),
                ('prediction_probability', models.FloatField()),
                ('long', models.DecimalField(decimal_places=10, max_digits=100)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=100)),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.crop')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
