# Generated by Django 5.1.6 on 2025-02-24 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='_yield',
            new_name='crop_yield',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='api_id',
        ),
    ]
