# Generated by Django 5.1.6 on 2025-02-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_rename__yield_crop_crop_yield_remove_crop_api_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplants',
            old_name='long',
            new_name='lon',
        ),
    ]
