# Generated by Django 5.1.6 on 2025-03-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0003_rename_long_userplants_lon"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="days_to_yield",
            field=models.IntegerField(default=100),
        ),
    ]
